Added tests of installation and usage.

diff --git a/bin/output b/bin/output
--- a/bin/output
+++ b/bin/output
@@ -9,7 +9,8 @@ function log {
   echo -e "\x1B[32m⬟ QC:\x1B[39m $1"
 }
 
+FAILURE_MESSAGE="Package check failed!"
 function fail {
-  echo -e "\x1B[41m\x1B[30m⬟ Trussle QC:\x1B[21m Package check failed! ⬟ \x1B[0m"
-  exit
+  echo -e "\x1B[41m\x1B[30m⬟ Trussle QC:\x1B[21m $FAILURE_MESSAGE ⬟ \x1B[0m"
+  exit 1
 }
